---
networks:
  - (( append ))
  - name: (( concat $OCFP_ENV_NAME "-bosh" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        gateway: (( grab meta.ocfp.net.bosh.gateway ))
        azs: [ z1 ]
        dns: [ (( grab meta.ocfp.net.bosh.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 " - " meta.ocfp.iaas.subnets[0].cidr.prefix ".9" ))
          - (( concat meta.ocfp.iaas.subnets[0].cidr.prefix ".11 - " meta.ocfp.iaas.subnets[0].cidr.ip_n ))

