---
meta:
  scale: (( grab $OCFP_ENV_SCALE ))

  ocfp:
    env:
      type: (( grab $OCFP_ENV_TYPE ))
      name: (( grab $OCFP_ENV_NAME ))
      region: (( grab $OCFP_ENV_REGION ))
      iaas: (( grab $OCFP_ENV_IAAS ))

    vault:
      env:
        path: (( concat $OCFP_VAULT_ENV_PATH "/" $OCFP_KIT ))
        tf_path: (( concat $OCFP_VAULT_TF_PATH "/" $OCFP_KIT ))

    net:
      bosh:
        gateway: (( vault meta.ocfp.vault.env.tf_path "/net/bosh:gateway" ))
        dns: (( vault meta.ocfp.vault.env.tf_path "/net/bosh:dns" ))
        ip: (( vault meta.ocfp.vault.env.tf_path "/net/bosh:ip" ))

    iaas:
      subnets:
        - id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:id" ))
          availability_zone: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:availability_zone" ))
          cidr:
            id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:id" ))
            block: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:cidr_block" ))
            prefix: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:cidr_prefix" ))
            ip_count: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:ip_count" ))
            ips: (( ips meta.ocfp.iaas.subnets[0].cidr.ip_0 1 meta.ocfp.iaas.subnets[0].cidr.ip_count ))
            ip_0: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:ip_0" ))
            ip_n: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0:ip_n" ))

        - id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:id" ))
          availability_zone: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:availability_zone" ))
          cidr:
            id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:id" ))
            block: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:cidr_block" ))
            prefix: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:cidr_prefix" ))
            ip_count: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:ip_count" ))
            ips: (( ips meta.ocfp.iaas.subnets[1].cidr.ip_0 1 meta.ocfp.iaas.subnets[1].cidr.ip_count ))
            ip_0: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:ip_0" ))
            ip_n: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1:ip_n" ))

        - id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:id" ))
          availability_zone: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:availability_zone" ))
          cidr:
            id: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:id" ))
            block: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:cidr_block" ))
            prefix: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:cidr_prefix" ))
            ip_count: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:ip_count" ))
            ips: (( ips meta.ocfp.iaas.subnets[2].cidr.ip_0 1 meta.ocfp.iaas.subnets[2].cidr.ip_count ))
            ip_0: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:ip_0" ))
            ip_n: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2:ip_n" ))

