---
meta:
  ocfp:
    vault:
      env:
        path: (( concat $OCFP_VAULT_ENV_PATH "/" $OCFP_KIT ))
        tf_path: (( concat $OCFP_VAULT_TF_PATH "/" $OCFP_KIT ))

    region: (( vault meta.ocfp.vault.env.tf_path "/bosh/iaas/region:name" ))

    bosh:
      access_key:  (( vault meta.ocfp.vault.env.tf_path "/bosh/iam/bosh:access_key" ))
      secret_key: (( vault meta.ocfp.vault.env.tf_path "/bosh/iam/bosh:secret_key" ))
      default_key_name: (( grab meta.ocfp.vault.env.tf_path "/bosh/keys/bosh:keypair_name" ))

    iaas:
      name: (( grab ${OCFP_IAAS} ))
      sgs:
        default:
          id: (( vault meta.ocfp.vault.env.tf_path "/bosh/iaas/sgs/default:id" ))

