---
meta:
  ocfp:
    vault:
      env:
        name: (( grab $OCFP_ENV_NAME ))
        path: (( concat $OCFP_VAULT_ENV_PATH "/" $OCFP_KIT ))
        tf_path: (( concat $OCFP_VAULT_TF_PATH "/" $OCFP_KIT ))

    region: (( vault meta.ocfp.vault.env.tf_path "/iaas/region:name" ))

    bosh:
      access_key:  (( vault meta.ocfp.vault.env.tf_path "/iam/bosh:access_key" ))
      secret_key: (( vault meta.ocfp.vault.env.tf_path "/iam/bosh:secret_key" ))
      default_key_name: (( vault meta.ocfp.vault.env.tf_path "/keys/bosh:keypair_name" ))

    iaas:
      name: (( grab $OCFP_IAAS ))
      sgs:
        default:
          id: (( vault meta.ocfp.vault.env.tf_path "/iaas/sgs/default:id" ))

