---
azs:
  - (( append ))
  - name: (( concat $OCFP_ENV_NAME "-z1" ))
    cloud_properties: 
      availability_zone: (( grab meta.ocfp.iaas.subnets[0].availability_zone ))
  - name: (( concat $OCFP_ENV_NAME "-z2" ))
    cloud_properties: 
      availability_zone: (( grab meta.ocfp.iaas.subnets[1].availability_zone ))
  - name: (( concat $OCFP_ENV_NAME "-z3" ))
    cloud_properties: 
      availability_zone: (( grab meta.ocfp.iaas.subnets[2].availability_zone ))

