---
meta:
  ocfp:
    iaas:
      ips:
        reserved:
          - bosh_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:bosh_a" ))
            bosh_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:bosh_b" ))
            vault_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:vault_a" ))
            vault_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:vault_b" ))
            jumpbox_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:jumpbox_a" ))
            jumpbox_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:jumpbox_b" ))
            concourse_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:concourse_a" ))
            concourse_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:concourse_b" ))
            prometheus_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:prometheus_a" ))
            prometheus_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:prometheus_b" ))
            shield_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:shield_a" ))
            shield_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:shield_b" ))
            compilation_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:compilation_a" ))
            compilation_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/mgmt/reserved:compilation_b" ))
          - bosh_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:bosh_a" ))
            bosh_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:bosh_b" ))
            vault_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:vault_a" ))
            vault_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:vault_b" ))
            jumpbox_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:jumpbox_a" ))
            jumpbox_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:jumpbox_b" ))
            concourse_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:concourse_a" ))
            concourse_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:concourse_b" ))
            prometheus_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:prometheus_a" ))
            prometheus_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:prometheus_b" ))
            doomsday_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:doomsday_a" ))
            doomsday_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:doomsday_b" ))
            concourse_workers_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:concourse_workers_a" ))
            concourse_workers_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/mgmt/reserved:concourse_workers_b" ))
          - bosh_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:bosh_a" ))
            bosh_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:bosh_b" ))
            vault_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:vault_a" ))
            vault_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:vault_b" ))
            jumpbox_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:jumpbox_a" ))
            jumpbox_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:jumpbox_b" ))
            concourse_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:concourse_a" ))
            concourse_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:concourse_b" ))
            prometheus_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:prometheus_a" ))
            prometheus_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:prometheus_b" ))
            concourse_workers_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:concourse_workers_a" ))
            concourse_workers_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/mgmt/reserved:concourse_workers_b" ))

