---
meta:
  ocfp:
    iaas:
      ips:
        reserved:
          - bosh_a:        (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:bosh_a" ))
            bosh_ip:       (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:bosh_ip" ))
            bosh_b:        (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:bosh_b" ))
            compilation_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:compilation_a" ))
            compilation_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:compilation_b" ))
            shield_a:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:shield_a" ))
            shield_ip:     (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:shield_ip" ))
            shield_b:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:shield_b" ))
            ocf_a:         (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/0/ips/ocf/reserved:ocf_a" ))

          - bosh_a:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:bosh_a" ))
            bosh_ip:     (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:bosh_ip" ))
            bosh_b:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:bosh_b" ))
            concourse_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:concourse_workers_a" ))
            concourse_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:concourse_workers_b" ))
            ocf_a:       (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:ocf_a" ))

          - bosh_a:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/ocf/reserved:bosh_a" ))
            bosh_ip:     (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/ocf/reserved:bosh_ip" ))
            bosh_b:      (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/ocf/reserved:bosh_b" ))
            concourse_a: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:concourse_workers_a" ))
            concourse_b: (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/1/ips/ocf/reserved:concourse_workers_b" ))
            ocf_a:       (( vault meta.ocfp.vault.env.tf_path "/iaas/subnets/ocfp/2/ips/ocf/reserved:ocf_a" ))
