---
################################################################################
# Management BOSH Director Cloud Config
################################################################################

################################################################################
# AZs
################################################################################
azs:
- name: (( concat $OCFP_ENV_NAME "-z1" ))
  cpi: (( grab $OCFP_ENV_NAME ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[0].availability_zone ))
- name: (( concat $OCFP_ENV_NAME "-z2" ))
  cpi: (( grab $OCFP_ENV_NAME ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[1].availability_zone ))
- name: (( concat $OCFP_ENV_NAME "-z3" ))
  cpi: (( grab $OCFP_ENV_NAME ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[2].availability_zone ))

################################################################################
# VM Types
################################################################################
vm_types:
- name: default-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.default.dev ))
    ephemeral_disk: { size: 4096,  type: gp3, encrypted: true }
- name: default-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.default.prod ))
    ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }
- name: compilation-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.compilation.dev ))
    ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }
- name: compilation-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.compilation.prod ))
    ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }
- name: bosh-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.bosh.dev ))
    ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }
- name: bosh-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.bosh.prod ))
    ephemeral_disk: { size: 131072, type: gp3, encrypted: true }
- name: vault-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.vault.dev ))
    ephemeral_disk: { size: 4096,  type: gp3, encrypted: true }
- name: vault-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.vault.prod ))
    ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }
- name: concourse-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.concourse.dev ))
    ephemeral_disk: { size: 65536, type: gp3, encrypted: true }
- name: concourse-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.concourse.prod ))
    ephemeral_disk: { size: 131072, type: gp3, encrypted: true }
- name: concourse-worker-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.concourse-worker.dev ))
    ephemeral_disk: { size: 65536, type: gp3, encrypted: true }
- name: concourse-worker-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.concourse-worker.prod ))
    ephemeral_disk: { size: 262144, type: gp3, encrypted: true }
- name: jumpbox-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.jumpbox.dev ))
    ephemeral_disk: { size: 4096, type: gp3, encrypted: true }
- name: jumpbox-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.jumpbox.prod ))
    ephemeral_disk: { size: 8192, type: gp3, encrypted: true }
- name: shield-dev
  cloud_properties:
    instance_type: (( grab meta.vm_types.shield.dev ))
    ephemeral_disk: { size: 4096,  type: gp3, encrypted: true }
- name: shield-prod
  cloud_properties:
    instance_type: (( grab meta.vm_types.shield.prod ))
    ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }

################################################################################
# Disk Types
################################################################################
disk_types:
- name: default-dev
  disk_size: (( grab meta.disk_sizes.default.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: default-prod
  disk_size: (( grab meta.disk_sizes.default.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: bosh-dev
  disk_size: (( grab meta.disk_sizes.bosh.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: bosh-prod
  disk_size: (( grab meta.disk_sizes.bosh.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: concourse-dev
  disk_size: (( grab meta.disk_sizes.concourse.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: concourse-prod
  disk_size: (( grab meta.disk_sizes.concourse.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: jumpbox-dev
  disk_size: (( grab meta.disk_sizes.jumpbox.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: jumpbox-prod
  disk_size: (( grab meta.disk_sizes.jumpbox.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: prometheus-dev
  disk_size: (( grab meta.disk_sizes.prometheus.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: prometheus-prod
  disk_size: (( grab meta.disk_sizes.prometheus.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: shield-dev
  disk_size: (( grab meta.disk_sizes.shield.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: shield-prod
  disk_size: (( grab meta.disk_sizes.shield.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: vault-dev
  disk_size: (( grab meta.disk_sizes.vault.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: vault-prod
  disk_size: (( grab meta.disk_sizes.vault.prod ))
  cloud_properties: { type: gp3, encrypted: true }
- name: doomsday-dev
  disk_size: (( grab meta.disk_sizes.doomsday.dev ))
  cloud_properties: { type: gp3, encrypted: true }
- name: doomsday-prod
  disk_size: (( grab meta.disk_sizes.doomsday.prod ))
  cloud_properties: { type: gp3, encrypted: true }

################################################################################
# Networks
################################################################################
networks:
################################################################################
# Network: Compilation
################################################################################
  - name: compilation
    type: manual
    subnets: 
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        gateway: (( grab meta.ocfp.net.bosh.gateway ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].compilation_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].compilation_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))

################################################################################
# Network: Management BOSH, ips: z{1}/.4
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-bosh" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].bosh_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].bosh_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))

################################################################################
# Network: Management Vault
#          ips: z{1,2,3}/subnet/.5
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-vault" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].vault_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].vault_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[1].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z2" ))
        dns:
          - (( grab meta.ocfp.iaas.subnets[1].cidr.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[1].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[1].vault_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[1].vault_b "-" meta.ocfp.iaas.subnets[1].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[2].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z3" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[2].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[2].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[2].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[2].vault_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[2].vault_b "-" meta.ocfp.iaas.subnets[2].cidr.ip_n ))

################################################################################
# Network: Management Jumpbox, ips: z{1,2,3}/subnet/.6
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-jumpbox" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].jumpbox_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].jumpbox_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[1].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z2" ))
        dns:
          - (( grab meta.ocfp.iaas.subnets[1].cidr.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[1].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[1].jumpbox_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[1].jumpbox_b "-" meta.ocfp.iaas.subnets[1].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[2].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z3" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[2].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[2].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[2].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[2].jumpbox_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[2].jumpbox_b "-" meta.ocfp.iaas.subnets[2].cidr.ip_n ))

################################################################################
# Network: Management Concourse, ips: z{1,2,3}/subnet/.7
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-concourse-web" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].concourse_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].concourse_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))
        #static:
        #  - (( concat meta.ocfp.iaas.ips.reserved[0].concourse_ip ))

  - name: (( concat $OCFP_ENV_NAME "-concourse" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[1].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z2" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[1].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[1].concourse_c ))
          - (( concat meta.ocfp.iaas.ips.reserved[1].concourse_d "-" meta.ocfp.iaas.subnets[1].cidr.ip_n ))

      - range: (( grab meta.ocfp.iaas.subnets[2].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z3" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[2].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[2].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[2].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[2].concourse_c ))
          - (( concat meta.ocfp.iaas.ips.reserved[2].concourse_d "-" meta.ocfp.iaas.subnets[2].cidr.ip_n ))

################################################################################
# Network: Management Prometheus, ips: z{1,2,3}/subnet/.8
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-prometheus" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].prometheus_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].prometheus_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[1].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z2" ))
        dns:
          - (( grab meta.ocfp.iaas.subnets[1].cidr.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[1].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[1].prometheus_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[1].prometheus_b "-" meta.ocfp.iaas.subnets[1].cidr.ip_n ))
      - range: (( grab meta.ocfp.iaas.subnets[2].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z3" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[2].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[2].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[2].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[2].prometheus_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[2].prometheus_b "-" meta.ocfp.iaas.subnets[2].cidr.ip_n ))

################################################################################
# Network: Management SHIELD, ips: z{1}/subnet/.10
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-shield" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[0].cidr.block ))
        az: (( concat $OCFP_ENV_NAME "-z1" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[0].shield_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].shield_b "-" meta.ocfp.iaas.subnets[0].cidr.ip_n ))
        static:
          - (( grab meta.ocfp.iaas.ips.reserved[0].shield_ip ))

################################################################################
# Network: Management Doomsday, ips: z{2}/subnet/.10
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-doomsday" ))
    type: manual
    subnets:
      - range: (( grab meta.ocfp.iaas.subnets[1].cidr.block ))
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        az: (( concat $OCFP_ENV_NAME "-z2" ))
        dns:
          - (( grab meta.ocfp.iaas.vpc.dns ))
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[1].cidr.ip_0 "-" meta.ocfp.iaas.ips.reserved[1].doomsday_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[1].doomsday_b "-" meta.ocfp.iaas.subnets[1].cidr.ip_n ))

################################################################################
# Compilation Settings
################################################################################
compilation:
  az: (( concat $OCFP_ENV_NAME "-z1" ))
  network: compilation
  vm_type: (( concat "compilation-" meta.scale ))
  workers: 6
  reuse_compilation_vms: true

################################################################################
# Compilation Settings
################################################################################
vm_extensions:
  - name: vault-lb
    cloud_properties:
      lb_target_groups:
        - ocfp-mgmt-vault-lb-tg
  - name: concourse-lb
    cloud_properties:
      lb_target_groups:
        - ocfp-mgmt-concourse-lb-tg
  - name: bosh-lb
    cloud_properties:
      lb_target_groups:
        - ocfp-mgmt-bosh-lb-tg
  - name: doomsday-lb
    cloud_properties:
      lb_target_groups:
        - ocfp-mgmt-doomsday-lb-tg

