---
################################################################################
# OCF Env BOSH Director Cloud Config
################################################################################

################################################################################
# AZs
################################################################################
azs:
- name: (( concat $OCFP_ENV_NAME "-z1" ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[0].availability_zone ))
- name: (( concat $OCFP_ENV_NAME "-z2" ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[1].availability_zone ))
- name: (( concat $OCFP_ENV_NAME "-z3" ))
  cloud_properties: 
    availability_zone: (( grab meta.ocfp.iaas.subnets[2].availability_zone ))

################################################################################
# VM Types
################################################################################
vm_types:
- { name: default-dev,       cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 51200,  type: gp3, encrypted: true }}}
- { name: default-prod,      cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 51200,  type: gp3, encrypted: true }}}
- { name: compilation-dev,   cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: compilation-prod,  cloud_properties: { instance_type: c6i.xlarge, ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: bosh-dev,          cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: bosh-prod,         cloud_properties: { instance_type: m6i.4xlarge,ephemeral_disk: { size: 131072, type: gp3, encrypted: true }}}
- { name: api-dev,           cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: api-prod,          cloud_properties: { instance_type: m5.large,   ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }}}
- { name: as-api-dev,        cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-api-prod,       cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-broker-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-broker-prod,    cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-collector-dev,  cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-collector-prod, cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-engine-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-engine-prod,    cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-operator-dev,   cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-operator-prod,  cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-scaler-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-scaler-prod,    cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-scheduler-dev,  cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: as-scheduler-prod, cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: bbs-dev,           cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: bbs-prod,          cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: blobstore-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: blobstore-prod,    cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: cc-worker-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: cc-worker-prod,    cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: credhub-dev,       cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: credhub-prod,      cloud_properties: { instance_type: r5.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: diego-cell-dev,    cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: diego-cell-prod,   cloud_properties: { instance_type: r5.2xlarge, ephemeral_disk: { size: 262144, type: gp3, encrypted: true }}}
- { name: diego-api-dev,     cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: diego-api-prod,    cloud_properties: { instance_type: c5.2xlarge, ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }}}
- { name: dopper-dev,        cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: dopper-prod,       cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }}}
- { name: errand-dev,        cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: errand-prod,       cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: haproxy-dev,       cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: haproxy-prod,      cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: log-api-dev,       cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: log-api-prod,      cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }}}
- { name: loggregator-dev,   cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: loggregator-prod,  cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 32768,  type: gp3, encrypted: true }}}
- { name: nats-dev,          cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: nats-prod,         cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: postgres-dev,      cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}
- { name: postgres-prod,     cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 65536,  type: gp3, encrypted: true }}}
- { name: router-dev,        cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: router-prod,       cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: scheduler-dev,     cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: scheduler-prod,    cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: syslogger-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: syslogger-prod,    cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: tcp-router-dev,    cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: tcp-router-prod,   cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: uaa-dev,           cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,   type: gp3, encrypted: true }}}
- { name: uaa-prod,          cloud_properties: { instance_type: c5.large,   ephemeral_disk: { size: 16384,  type: gp3, encrypted: true }}}

- { name: blacksmith-dev,                  cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-prod,                 cloud_properties: { instance_type: m6i.large,  ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-redis-small-dev,      cloud_properties: { instance_type: t3.small,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-redis-small-prod,     cloud_properties: { instance_type: c5.large,   ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-redis-medium-dev,     cloud_properties: { instance_type: t3.medium,  ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-redis-medium-prod,    cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-redis-large-dev,      cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-redis-large-prod,     cloud_properties: { instance_type: c5.2xlarge, ephemeral_disk: { size: 32768, type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-small-dev,   cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-small-prod,  cloud_properties: { instance_type: c5.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-medium-dev,  cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-medium-prod, cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-large-dev,   cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-rabbitmq-large-prod,  cloud_properties: { instance_type: c5.2xlarge, ephemeral_disk: { size: 32768, type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-small-dev,   cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-small-prod,  cloud_properties: { instance_type: c5.large,   ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-medium-dev,  cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 8192,  type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-medium-prod, cloud_properties: { instance_type: c5.xlarge,  ephemeral_disk: { size: 32768, type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-large-dev,   cloud_properties: { instance_type: t3.large,   ephemeral_disk: { size: 16384, type: gp3, encrypted: true }}}
- { name: blacksmith-postgres-large-prod,  cloud_properties: { instance_type: c5.2xlarge, ephemeral_disk: { size: 65536, type: gp3, encrypted: true }}}

################################################################################
# Disk Types
################################################################################
disk_types:
- { name: default-dev,    disk_size: 8192,   cloud_properties: { type: gp3, encrypted: true }}
- { name: default-prod,   disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: bosh-dev,       disk_size: 32768,  cloud_properties: { type: gp3, encrypted: true }}
- { name: bosh-prod,      disk_size: 65536,  cloud_properties: { type: gp3, encrypted: true }}
- { name: consul-dev,     disk_size: 4096,   cloud_properties: { type: gp3, encrypted: true }}
- { name: consul-prod,    disk_size: 8192,   cloud_properties: { type: gp3, encrypted: true }}
- { name: postgres-dev,   disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: postgres-prod,  disk_size: 65536,  cloud_properties: { type: gp3, encrypted: true }}
- { name: blobstore-dev,  disk_size: 32768,  cloud_properties: { type: gp3, encrypted: true }}
- { name: blobstore-prod, disk_size: 524288, cloud_properties: { type: gp3, encrypted: true }}
- { name: shield-dev,     disk_size: 8192,   cloud_properties: { type: gp3, encrypted: true }}
- { name: shield-prod,    disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: redis-dev,      disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: redis-prod,     disk_size: 32768,  cloud_properties: { type: gp3, encrypted: true }}
- { name: rabbitmq-dev,   disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: rabbitmq-prod,  disk_size: 32768,  cloud_properties: { type: gp3, encrypted: true }}
- { name: minio-dev,      disk_size: 16384,  cloud_properties: { type: gp3, encrypted: true }}
- { name: minio-prod,     disk_size: 65536,  cloud_properties: { type: gp3, encrypted: true }}

################################################################################
# Networks
################################################################################
networks:

################################################################################
# Network: Compilation
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-compilation" ))
    type: manual
    subnets: 
      - range: (( grab meta.iaas.subnets[0].cidr.block ))
        azs: [ (( concat $OCFP_ENV_NAME "-z1" )) ]
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        dns: [ (( grab meta.ocfp.iaas.subnets[0].cidr.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 " - " meta.ocfp.iaas.ips.reserved[0].compilation_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].compilation_b " - " meta.ocfp.iaas.subnets[0].cidr.ip_n ))

################################################################################
# Network: OCF Env BOSH, ips: z{1}/.10
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-bosh" ))
    type: manual
    subnets:
      - range: (( grab meta.iaas.subnets[0].cidr.block ))
        azs: [ (( concat $OCFP_ENV_NAME "-z1" )) ]
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        dns: [ (( grab meta.ocfp.iaas.subnets[0].cidr.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( concat meta.ocfp.iaas.subnets[0].cidr.ip_0 " - " meta.ocfp.iaas.ips.reserved[0].bosh_a ))
          - (( concat meta.ocfp.iaas.ips.reserved[0].bosh_b " - " meta.ocfp.iaas.subnets[0].cidr.ip_n ))

################################################################################
# Network: OCF
################################################################################
  - name: (( concat $OCFP_ENV_NAME "-ocf" ))
    type: manual
    subnets:
      - range: (( grab meta.iaas.subnets[0].cidr.block ))
        azs: [ (( concat $OCFP_ENV_NAME "-z1" )) ]
        gateway: (( grab meta.ocfp.iaas.subnets[0].cidr.gateway ))
        dns: [ (( grab meta.ocfp.iaas.subnets[0].cidr.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[0].id ))
        reserved:
          - (( meta.ocfp.iaas.subnets[0].cidr.ip_n - meta.ocfp.iaas.ips.reserved[0].ocf_a ))

      - range: (( grab meta.iaas.subnets[1].cidr.block ))
        azs: [ (( concat $OCFP_ENV_NAME "-z2" )) ]
        gateway: (( grab meta.ocfp.iaas.subnets[1].cidr.gateway ))
        dns: [ (( grab meta.ocfp.iaas.subnets[1].cidr.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[1].id ))
        reserved:
          - (( meta.ocfp.iaas.subnets[1].cidr.ip_n - meta.ocfp.iaas.ips.reserved[1].ocf_a ))

      - range: (( grab meta.iaas.subnets[2].cidr.block ))
        azs: [ (( concat $OCFP_ENV_NAME "-z3" )) ]
        gateway: (( grab meta.ocfp.iaas.subnets[2].cidr.gateway ))
        dns: [ (( grab meta.ocfp.iaas.subnets[2].cidr.dns )) ]
        cloud_properties:
          subnet: (( grab meta.ocfp.iaas.subnets[2].id ))
        reserved:
          - (( meta.ocfp.iaas.subnets[2].cidr.ip_n - meta.ocfp.iaas.ips.reserved[2].ocf_a ))

################################################################################
# Compilation Settings
################################################################################
compilation:
  az: (( concat $OCFP_ENV_NAME "-z2" ))
  network: (( concat $OCFP_ENV_NAME "-compilation" ))
  vm_type: (( concat "compilation-" meta.scale ))
  workers: 6
  reuse_compilation_vms: true

################################################################################
# Compilation Settings
################################################################################
vm_extensions:
  - name: cf-system-apps-tcp-lb
    cloud_properties:
      lb_target_group:
        - ocfp-ocf-cf-system-lb-tg
        - ocfp-ocf-cf-apps-lb-tg
  - name: cf-ssh-lb
    cloud_properties:
      lb_target_group:
        - ocfp-ocf-cf-ssh-lb-tg
  - name: cf-ssh-lb
    cloud_properties:
      lb_target_group:
        - ocfp-ocf-cf-ssh-lb-tg
  - name: blacksmith-lb
    cloud_properties:
      lb_target_group:
        - ocfp-ocf-blacksmith-lb-tg

